### ISSUE TITLE
Trapped doors

### ISSUE THREAD

**Issue by RandallDavis** [RandallDavis/roll20-roomScript#27]
- Door can be set to trapped / untapped by text command.
- Whisper to GM if trapped door is toggled.

**Comment by Fantell** [comment]
traps show a unique flash token when they are interacted with, and present the GM with a set trap off api button, and a disarm one, so that he can determine when to activate the 'trap' and print out whatever notes are attached.

**Comment by RandallDavis** [comment]
States:

If a door is unlocked, a trap can only go off when the door is toggled.

If a door is locked, a trap could go off when the door is interacted with (trap triggered but no toggle) or only when it is toggled (interacting with the locked door has no practical effect).

Options:

Unlocked untrapped: lock, set trap (toggle).
Locked, untrapped: unlock, set trap (toggle), set trap (interact).
Unlocked, trapped (toggle): lock, disarm (toggle), lock and make trap interactive.
Locked, trapped (toggle): unlock, disarm (toggle), change trap to interactive.
Locked, trapped (interact): unlock and change trap to toggle, change trap to toggle, disarm (interact), unlock and disarm (interact).

**Comment by RandallDavis** [comment]
As suggested, any time a trap is set, we can have an option of "detonate" that removes the trap but displays the trap animation.

**Comment by RandallDavis** [comment]
In play, there might be cases where the trap should be triggered when interacting with the lock. This is not the same as interacting with the door and is something that would have to be managed manually through gameplay (rules and conversation are both involved). This would require a gm to disarm or detonate the trap.

**Comment by RandallDavis** [comment]
This is done - there's no storing / displaying of text feature, but it's functional and visual.
